# Generated by Django 4.2.3 on 2023-07-13 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaderClient', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=64)),
                ('serialNumberEngine', models.CharField(max_length=64)),
                ('serialNumberTransmission', models.CharField(max_length=64)),
                ('serialNumberLeadingAxle', models.CharField(max_length=64)),
                ('serialNumberSteerAxle', models.CharField(max_length=64)),
                ('supplyContractNumDate', models.CharField(max_length=64)),
                ('dateOfShippingFactory', models.DateField()),
                ('recipient', models.CharField(max_length=64)),
                ('deliveryAddress', models.CharField(max_length=128)),
                ('equipment', models.CharField(max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaderapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authServiceCompany', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TechService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTechService', models.CharField(max_length=128)),
                ('dateTechService', models.DateField()),
                ('operatingTimeTech', models.FloatField()),
                ('numberWorkOrder', models.CharField(max_length=64)),
                ('dateWorkOrder', models.DateField()),
                ('loaderOnTechService', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loaderapp.loader')),
                ('techServiceCompany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.servicecompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModelTransmission', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSteerAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModelSteerAxle', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModelLoader', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelLeadingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModelLeadingAxle', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameModelEngine', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='loader',
            name='modelOfEngine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.modelengine'),
        ),
        migrations.AddField(
            model_name='loader',
            name='modelOfLeadingAxle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.modelleadingaxle'),
        ),
        migrations.AddField(
            model_name='loader',
            name='modelOfLoader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.modelloader'),
        ),
        migrations.AddField(
            model_name='loader',
            name='modelOfSteerAxle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.modelsteeraxle'),
        ),
        migrations.AddField(
            model_name='loader',
            name='modelOfTransmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.modeltransmission'),
        ),
        migrations.AddField(
            model_name='loader',
            name='serviceCompanyLoader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.servicecompany'),
        ),
        migrations.AddField(
            model_name='loader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFailure', models.DateField()),
                ('operatingTimeClaim', models.FloatField()),
                ('unitFailure', models.CharField(max_length=128)),
                ('detailsFailure', models.CharField(max_length=264)),
                ('methodRepair', models.CharField(max_length=128)),
                ('spareParts', models.CharField(max_length=128)),
                ('dateRepair', models.DateField()),
                ('loaderOnClaim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loaderapp.loader')),
                ('repairServiceCompany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loaderapp.servicecompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
