# Generated by Django 4.2.3 on 2023-07-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaderapp', '0002_alter_techservice_loaderontechservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='loaderOnClaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaderapp.loader'),
        ),
    ]
